#!/bin/sh

# 请把本文件放在/etc/hotplug.d/net/下，跟随sing-box启动生效

if [ "$ACTION" != "add" ] || [ "$INTERFACE" != "singbox_tun" ]; then
    exit 0
fi

sleep 2

# === 在下方定义您要旁路的 MAC 地址 ===
BYPASS_MACS="{ bc:24:11:bd:dd:43, bb:bb:bb:bb:bb:bb }"
# === 定义结束 ===


# --- 开始执行 nftables 操作 ---

nft add set inet sing-box bypass_mac_set { type ether_addr\; }
nft flush set inet sing-box bypass_mac_set
nft add element inet sing-box bypass_mac_set $BYPASS_MACS

nft add chain inet sing-box mac_bypass_chain
nft flush chain inet sing-box mac_bypass_chain
nft add rule inet sing-box mac_bypass_chain ether saddr @bypass_mac_set accept

# MAC 不匹配 -> 'return'
nft add rule inet sing-box mac_bypass_chain return

#    为 'prerouting' 链 (TCP) 插入 'jump'
LIST_PREROUTING=$(nft list chain inet sing-box prerouting 2>/dev/null)
if [ -n "$LIST_PREROUTING" ] && ! echo "$LIST_PREROUTING" | grep -q "jump mac_bypass_chain"; then
    nft insert rule inet sing-box prerouting jump mac_bypass_chain
fi

#    为 'prerouting_udp_icmp' 链 (UDP) 插入 'jump'
LIST_PREROUTING_UDP=$(nft list chain inet sing-box prerouting_udp_icmp 2>/dev/null)
if [ -n "$LIST_PREROUTING_UDP" ] && ! echo "$LIST_PREROUTING_UDP" | grep -q "jump mac_bypass_chain"; then
    nft insert rule inet sing-box prerouting_udp_icmp jump mac_bypass_chain
fi

exit 0
